### ISSUE TITLE
Redshirting Uses Recruiting Cost

### ISSUE THREAD

**Issue by destilla** [jonesguy14/footballcoach#44]
I'm sure this is a simple fix but I'm not familiar enough with the recruiting code and it's late, so I wanted to make a note of this in case you were able to get to it before me. If you choose to redshirt, you use the recruiting amount:

![image](https://cloud.githubusercontent.com/assets/11052658/14099646/2aa4cef8-f53c-11e5-90ac-8a05cf89a013.png)

I should have $7 left over:

![image](https://cloud.githubusercontent.com/assets/11052658/14099656/3f147474-f53c-11e5-9c2e-3a85d60379a8.png)

**Comment by jonesguy14** [comment]
Wow, yep thats a big oversight by me. I'll put out a hotfix today to the play store with that bug fixed and your news stories implemented.
