### ISSUE TITLE
April Fools Sticky on the Subreddit

### ISSUE THREAD

**Issue by destilla** [jonesguy14/footballcoach#54]
Gonna write one up and post it midnight PST since I already missed EST and just had the idea.

Every great game has a great fake April Fools update log :D

Ideas: Licensing Agreement with _some_ real teams, in game play calling, All-Century CFB rosters.

**Comment by destilla** [comment]
I think I've created a monster

**Comment by destilla** [comment]
https://www.reddit.com/r/FootballCoach/comments/4cuf1c/football_coach_141_out_now_licensing_for_real/

**Comment by jonesguy14** [comment]
Wow that is hilarious lol, great job! I was thinking of what we could do for April Fools but you knocked it out of the park, love your new flair too lmao

**Comment by destilla** [comment]
Hahaha, thanks man! I'm going to keep running with it throughout the day. I wanted to make it so that whenever you opened a Boise State home game log the whole thing was bright blue, but I couldn't figure out how to change the theme fast enough (or at all really). So I went with the next best thing.

Glad you're getting some laughs out of it
